### ISSUE TITLE
Upgrade path for roadie from 2 to 3 when upgrading Rails from 3 to 4

### ISSUE THREAD

**Issue by seddy** [Mange/roadie#113]
@Mange - apologies if this shouldn't be coming through as an issue but I wasn't sure where else would be the best place to ask!  Please redirect me as appropriate.

I'm upgrading a legacy application from Rails 3 to Rails 4 and I was wondering what the most sensible upgrade path would be.  Currently, we're running:

* Rails 3.2.22
* Roadie 2.3.4

We're in the process of upgrading to Rails 4.2.5.  However, Roadie 2.3.4 is not compatible with Rails 4, so we need to upgrade it.  My plan is to do this:

1. Upgrade Roadie to 2.4.3 (which *is* compatible with Rails 4)
1. Upgrade Rails 3 to Rails 4
1. Upgrade Roadie to latest 3.x version and pull in `roadie-rails`

Does this sound sensible, or is there some reason it would be better to do the full Roadie upgrade before the Rails one?  Are there any useful resources or guides for upgrading from Roadie 2 to 3 somewhere, I've had a google around but haven't been able to find anything so far.

**Comment by Mange** [comment]
Hi there!

This is a good place to have this in as it might help others as well. I have a label for "issues" like this. :-)

I think that sounds like a very reasonable plan, actually. The only reason to take a full Roadie upgrade first is that it's simpler than upgrading your framework. It also ensures that all the latest bugfixes come along, so your Rails upgrade might go over more smoothly.

Holding it off and doing Rails first is better because it optimizes for the most important upgrade first, and I think one should try to abide by the thinking of "later is often never"; maybe you never get the time to upgrade Rails again soon, so always pick the most important task to do (unless reordering saves a lot of time / cost).

Anyway, there's an upgrade guide in this very repo, but it was before 3.1 which is why you couldn't find it. [If you run `roadie 3.0` without `roadie-rails`, and `Rails` is defined, you'll get a long error about this upgrade](https://github.com/Mange/roadie/blob/v3.0.5/lib/roadie/upgrade_guide.rb). It redirects you to [a URL that explains how to do it using `roadie-rails`](https://github.com/Mange/roadie-rails/blob/master/Upgrading.md).

Let me know if you need any assistance from me.

**Comment by seddy** [comment]
Thanks for that @Mange, very much appreciated :)!  The upgrade guide looks good, I'll go to 2.4.3 and carry on with upgrading Rails then and let you know if I have any more questions when I come to upgrading to roadie 3.
