### ISSUE TITLE
css_parser is locked to 1.4.x, 1.5.x is out

### ISSUE THREAD

**Issue by bbenezech** [Mange/roadie#141]
Same thing as nokogiri, do they have have issues with Semver?
Lock should be 1.x, x>=4 in the Semver spirit.

**Comment by Mange** [comment]
In the case of css_parser, I asked about it here but couldn't really understand the answer fully.
premailer/css_parser#76

By that point I read it that they wanted to bump versions however they wanted, but on re-reading it it sounds more like "I don't want to say in the README how I bump the version". Maybe you could help me understand the comment. 

I can't remember what the problem was with Nokigiri. If they are following semver, we should be able to unlock as well.

**Comment by bbenezech** [comment]
I think @grosser meant something along the lines: (correct me if I'm wrong)
- it's Semver unless I screw up
- I won't add repositories meta crap (I hate badges or drama over CoC PRs)

He really could have just said yes.

**Comment by grosser** [comment]
semver-ish so should be safe to unlock ... no guarantees that every tiny api change will be a major bump but trying to keep things stable

**Comment by bbenezech** [comment]
@grosser Thx!

**Comment by Mange** [comment]
Thank you for clarifying. I'll unlock the dependency! ♥ 

> I hate badges or drama over CoC PRs

That is at least something that describes me. Sorry if my original question sounded like one of those. That was not my intention.

**Comment by Mange** [comment]
I just released version 3.2.2 with a fix for this included. Thank you for your help! :heart:
