### ISSUE TITLE
Support CSS custom properties (variables)

### ISSUE THREAD

**Issue by TSMMark** [Mange/roadie#166]
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

Is it possible to support css variables? Goal is to dynamically change color theme based on user preference, without having individual css file for each user.

**Comment by TSMMark** [comment]
After testing, currently Roadie inlines the CSS variable style, but barely any email clients support custom properties: https://www.caniemail.com/features/css-variables/

I think it would be great if Roadie could resolve the custom property value and inline it. 

Is that possible?

**Comment by Mange** [comment]
No, that is out of scope for roadie. If we do that then we suddenly have to do a lot more complicated work around understanding CSS and trying to apply the more complicated parts. Roadie is just doing some "mechanical work" that a developer would have to do anyway in order to get basic styles working, not doing all the work for super advanced styles.

Instead I suggest you inline those styles as normal style tags and work from there. It's probably a few more years before any email clients will support this anyway.
