### ISSUE TITLE
Use HTML instead of XHTML

### ISSUE THREAD

**Issue by Mange** [Mange/roadie#24]
XHTML isn't understood by most email clients. Roadie should not add XHTML boilerplate when missing!

**Comment by vrinek** [comment]
I stumbled upon a few validation issues regarding this one. We send emails as XHTML right now and W3C's validator treats self-closing tags with no trailing slash as errors. I monkey patched `Roadie::Document#transform` to end with `dom.dup.to_xhtml` and it solved the issue for me.

> XHTML isn't understood by most email clients.

Could you share a link on the resource that claims this?

I assume that since this was merged in 2013, things may have changed.

**Comment by Mange** [comment]
XHTML isn't even understood by most Web browsers. At the height of
adoption, only a few of the major browsers did, and most people publishing
XHTML actually sent them as text/html instead of application/xml, since
small markup errors would just render a XML Parsing error instead of a
mostly working site. For this reason, even the browsers supporting XHTML
treated it as HTML4 with quirks (not to be confused with "quirks mode").

HTML5 began because WhatWG decided that XHTML was dead in the water and not
the way forward. Since HTML5 "won", XHTML is only treated as legacy in most
browsers.

Considering that browsers treat it the way they do, I assume email clients
(who don't implement most of the standards) doesn't support it either. If
you are having problems with HTML5, it's more likely that you should output
HTML4 rather than XML.

I'm open to facts that disprove my stance, however. I have never heard of
an email client supporting XHTML correctly (and of they did, it should be
very likely that they support HTML5 now as "future Web technology" was
important to them), but I know it's all Argument from Ignorance.

ons 20 jan. 2016 13:23 Kostas <notifications@github.com> skrev:
